/**
 * 文学段落库种子数据
 * 包含10位中外作家及其代表性段落
 */

// 作家数据
export const AUTHORS_DATA = [
  {
    name: '李白',
    nameEn: 'Li Bai',
    era: '古代',
    nationality: '中国',
    styleTags: ['浪漫', '豪放', '飘逸'],
    bio: '唐代伟大的浪漫主义诗人，被后人誉为"诗仙"',
    plantType: '松树',
    plantSymbol: '傲骨凌云，不畏风霜',
  },
  {
    name: '苏轼',
    nameEn: 'Su Shi',
    era: '古代',
    nationality: '中国',
    styleTags: ['豁达', '深情', '哲理'],
    bio: '北宋文学家、书画家，"唐宋八大家"之一',
    plantType: '竹子',
    plantSymbol: '虚心有节，宁折不弯',
  },
  {
    name: '李清照',
    nameEn: 'Li Qingzhao',
    era: '古代',
    nationality: '中国',
    styleTags: ['婉约', '细腻', '愁思'],
    bio: '宋代女词人，婉约词派代表，号易安居士',
    plantType: '莲花',
    plantSymbol: '出淤泥而不染，濯清涟而不妖',
  },
  {
    name: '鲁迅',
    nameEn: 'Lu Xun',
    era: '近现代',
    nationality: '中国',
    styleTags: ['犀利', '深刻', '批判'],
    bio: '中国现代文学的奠基人，思想家、革命家',
    plantType: '梅花',
    plantSymbol: '凌寒独自开，暗香浮动',
  },
  {
    name: '林徽因',
    nameEn: 'Lin Huiyin',
    era: '近现代',
    nationality: '中国',
    styleTags: ['温婉', '诗意', '浪漫'],
    bio: '中国著名建筑师、诗人、作家',
    plantType: '玫瑰',
    plantSymbol: '娇艳芬芳，热烈深情',
  },
  {
    name: '莎士比亚',
    nameEn: 'William Shakespeare',
    era: '古代',
    nationality: '英国',
    styleTags: ['戏剧', '深邃', '人性'],
    bio: '英国文艺复兴时期伟大的剧作家、诗人',
    plantType: '橡树',
    plantSymbol: '坚韧不拔，庇护众生',
  },
  {
    name: '泰戈尔',
    nameEn: 'Rabindranath Tagore',
    era: '近现代',
    nationality: '印度',
    styleTags: ['哲思', '灵性', '自然'],
    bio: '印度诗人、哲学家，诺贝尔文学奖获得者',
    plantType: '水仙',
    plantSymbol: '清雅脱俗，灵性绽放',
  },
  {
    name: '海明威',
    nameEn: 'Ernest Hemingway',
    era: '近现代',
    nationality: '美国',
    styleTags: ['简洁', '硬汉', '冒险'],
    bio: '美国作家、记者，诺贝尔文学奖获得者',
    plantType: '仙人掌',
    plantSymbol: '坚韧顽强，沙漠之花',
  },
  {
    name: '川端康成',
    nameEn: 'Yasunari Kawabata',
    era: '近现代',
    nationality: '日本',
    styleTags: ['物哀', '唯美', '细腻'],
    bio: '日本新感觉派作家，诺贝尔文学奖获得者',
    plantType: '橄榄树',
    plantSymbol: '和平宁静，岁月静好',
  },
  {
    name: '加缪',
    nameEn: 'Albert Camus',
    era: '近现代',
    nationality: '法国',
    styleTags: ['存在', '荒诞', '反抗'],
    bio: '法国作家、哲学家，诺贝尔文学奖获得者',
    plantType: '向日葵',
    plantSymbol: '向阳而生，热爱生命',
  },
];

// 作品数据 (authorName用于关联)
export const WORKS_DATA = [
  { authorName: '李白', title: '将进酒', type: '诗词', era: '唐代' },
  { authorName: '李白', title: '静夜思', type: '诗词', era: '唐代' },
  { authorName: '李白', title: '行路难', type: '诗词', era: '唐代' },
  { authorName: '苏轼', title: '水调歌头', type: '诗词', era: '宋代' },
  { authorName: '苏轼', title: '念奴娇·赤壁怀古', type: '诗词', era: '宋代' },
  { authorName: '苏轼', title: '定风波', type: '诗词', era: '宋代' },
  { authorName: '李清照', title: '如梦令', type: '诗词', era: '宋代' },
  { authorName: '李清照', title: '声声慢', type: '诗词', era: '宋代' },
  { authorName: '李清照', title: '一剪梅', type: '诗词', era: '宋代' },
  { authorName: '鲁迅', title: '野草', type: '散文', era: '民国' },
  { authorName: '鲁迅', title: '朝花夕拾', type: '散文', era: '民国' },
  { authorName: '林徽因', title: '你是人间的四月天', type: '诗词', era: '民国' },
  { authorName: '莎士比亚', title: '哈姆雷特', type: '戏剧', era: '文艺复兴' },
  { authorName: '莎士比亚', title: '十四行诗', type: '诗词', era: '文艺复兴' },
  { authorName: '泰戈尔', title: '飞鸟集', type: '诗词', era: '近代' },
  { authorName: '泰戈尔', title: '新月集', type: '诗词', era: '近代' },
  { authorName: '海明威', title: '老人与海', type: '小说', era: '现代' },
  { authorName: '川端康成', title: '雪国', type: '小说', era: '现代' },
  { authorName: '川端康成', title: '古都', type: '小说', era: '现代' },
  { authorName: '加缪', title: '局外人', type: '小说', era: '现代' },
  { authorName: '加缪', title: '西西弗神话', type: '散文', era: '现代' },
];

// 文学段落数据 (authorName和workTitle用于关联)
export const PASSAGES_DATA = [
  // ========== 李白 ==========
  {
    authorName: '李白',
    workTitle: '将进酒',
    content: '君不见黄河之水天上来，奔流到海不复回。君不见高堂明镜悲白发，朝如青丝暮成雪。',
    emotionTags: ['豪迈', '感慨', '悲壮'],
    imageryTags: ['黄河', '明镜', '白发'],
    sceneTags: ['自然', '室内'],
    themeTags: ['时光', '人生'],
  },
  {
    authorName: '李白',
    workTitle: '将进酒',
    content: '人生得意须尽欢，莫使金樽空对月。天生我材必有用，千金散尽还复来。',
    emotionTags: ['豪放', '自信', '洒脱'],
    imageryTags: ['金樽', '月亮'],
    sceneTags: ['宴饮'],
    themeTags: ['人生', '自我'],
  },
  {
    authorName: '李白',
    workTitle: '静夜思',
    content: '床前明月光，疑是地上霜。举头望明月，低头思故乡。',
    emotionTags: ['思念', '孤独', '惆怅'],
    imageryTags: ['月光', '霜'],
    sceneTags: ['夜晚', '室内'],
    themeTags: ['乡愁', '思念'],
  },
  {
    authorName: '李白',
    workTitle: '行路难',
    content: '长风破浪会有时，直挂云帆济沧海。',
    emotionTags: ['希望', '坚定', '豪迈'],
    imageryTags: ['风', '浪', '云帆', '大海'],
    sceneTags: ['海洋'],
    themeTags: ['理想', '奋斗'],
  },
  {
    authorName: '李白',
    workTitle: '行路难',
    content: '行路难，行路难，多歧路，今安在？',
    emotionTags: ['迷茫', '困惑', '焦虑'],
    imageryTags: ['道路'],
    sceneTags: ['旅途'],
    themeTags: ['人生', '选择'],
  },

  // ========== 苏轼 ==========
  {
    authorName: '苏轼',
    workTitle: '水调歌头',
    content: '明月几时有？把酒问青天。不知天上宫阙，今夕是何年。',
    emotionTags: ['思念', '感慨', '超脱'],
    imageryTags: ['明月', '酒', '天空'],
    sceneTags: ['夜晚', '户外'],
    themeTags: ['人生', '哲思'],
  },
  {
    authorName: '苏轼',
    workTitle: '水调歌头',
    content: '人有悲欢离合，月有阴晴圆缺，此事古难全。但愿人长久，千里共婵娟。',
    emotionTags: ['豁达', '思念', '祝福'],
    imageryTags: ['月亮'],
    sceneTags: ['夜晚'],
    themeTags: ['人生', '亲情'],
  },
  {
    authorName: '苏轼',
    workTitle: '念奴娇·赤壁怀古',
    content: '大江东去，浪淘尽，千古风流人物。',
    emotionTags: ['豪迈', '感慨', '怀古'],
    imageryTags: ['江水', '浪'],
    sceneTags: ['江边'],
    themeTags: ['历史', '英雄'],
  },
  {
    authorName: '苏轼',
    workTitle: '定风波',
    content: '莫听穿林打叶声，何妨吟啸且徐行。竹杖芒鞋轻胜马，谁怕？一蓑烟雨任平生。',
    emotionTags: ['豁达', '洒脱', '从容'],
    imageryTags: ['雨', '竹杖', '蓑衣'],
    sceneTags: ['雨中', '山林'],
    themeTags: ['人生', '态度'],
  },
  {
    authorName: '苏轼',
    workTitle: '定风波',
    content: '回首向来萧瑟处，归去，也无风雨也无晴。',
    emotionTags: ['超脱', '平静', '释然'],
    imageryTags: ['风雨'],
    sceneTags: ['户外'],
    themeTags: ['人生', '心境'],
  },

  // ========== 李清照 ==========
  {
    authorName: '李清照',
    workTitle: '如梦令',
    content: '昨夜雨疏风骤，浓睡不消残酒。试问卷帘人，却道海棠依旧。知否，知否？应是绿肥红瘦。',
    emotionTags: ['惆怅', '伤感', '细腻'],
    imageryTags: ['雨', '风', '海棠', '酒'],
    sceneTags: ['室内', '清晨'],
    themeTags: ['春天', '感伤'],
  },
  {
    authorName: '李清照',
    workTitle: '声声慢',
    content: '寻寻觅觅，冷冷清清，凄凄惨惨戚戚。乍暖还寒时候，最难将息。',
    emotionTags: ['孤独', '悲伤', '凄凉'],
    imageryTags: ['寒冷'],
    sceneTags: ['室内'],
    themeTags: ['孤独', '思念'],
  },
  {
    authorName: '李清照',
    workTitle: '声声慢',
    content: '梧桐更兼细雨，到黄昏、点点滴滴。这次第，怎一个愁字了得！',
    emotionTags: ['愁苦', '悲伤', '无奈'],
    imageryTags: ['梧桐', '细雨', '黄昏'],
    sceneTags: ['雨中', '黄昏'],
    themeTags: ['愁绪', '孤独'],
  },
  {
    authorName: '李清照',
    workTitle: '一剪梅',
    content: '红藕香残玉簟秋，轻解罗裳，独上兰舟。云中谁寄锦书来？雁字回时，月满西楼。',
    emotionTags: ['思念', '孤独', '期盼'],
    imageryTags: ['荷花', '兰舟', '大雁', '月亮'],
    sceneTags: ['秋天', '水边'],
    themeTags: ['相思', '离别'],
  },
  {
    authorName: '李清照',
    workTitle: '一剪梅',
    content: '花自飘零水自流，一种相思，两处闲愁。此情无计可消除，才下眉头，却上心头。',
    emotionTags: ['相思', '愁苦', '无奈'],
    imageryTags: ['花', '水'],
    sceneTags: ['自然'],
    themeTags: ['爱情', '思念'],
  },

  // ========== 鲁迅 ==========
  {
    authorName: '鲁迅',
    workTitle: '野草',
    content: '当我沉默着的时候，我觉得充实；我将开口，同时感到空虚。',
    emotionTags: ['沉思', '矛盾', '深刻'],
    imageryTags: [],
    sceneTags: ['内心'],
    themeTags: ['自我', '表达'],
  },
  {
    authorName: '鲁迅',
    workTitle: '野草',
    content: '绝望之为虚妄，正与希望相同。',
    emotionTags: ['深刻', '哲思', '冷峻'],
    imageryTags: [],
    sceneTags: ['内心'],
    themeTags: ['人生', '哲理'],
  },
  {
    authorName: '鲁迅',
    workTitle: '野草',
    content: '我愿意这样，朋友——我独自远行，不但没有你，并且再没有别的影在黑暗里。只有我被黑暗沉没，那世界全属于我自己。',
    emotionTags: ['孤独', '决绝', '自由'],
    imageryTags: ['黑暗', '影子'],
    sceneTags: ['夜晚'],
    themeTags: ['孤独', '自我'],
  },
  {
    authorName: '鲁迅',
    workTitle: '朝花夕拾',
    content: '我有一时，曾经屡次忆起儿时在故乡所吃的蔬果：菱角、罗汉豆、茭白、香瓜。凡这些，都是极其鲜美可口的；都曾是使我思乡的蛊惑。',
    emotionTags: ['怀念', '温暖', '思乡'],
    imageryTags: ['蔬果', '故乡'],
    sceneTags: ['回忆'],
    themeTags: ['童年', '乡愁'],
  },

  // ========== 林徽因 ==========
  {
    authorName: '林徽因',
    workTitle: '你是人间的四月天',
    content: '我说你是人间的四月天；笑响点亮了四面风；轻灵在春的光艳中交舞着变。',
    emotionTags: ['喜悦', '温柔', '浪漫'],
    imageryTags: ['四月', '春天', '风', '光'],
    sceneTags: ['春天'],
    themeTags: ['爱情', '美好'],
  },
  {
    authorName: '林徽因',
    workTitle: '你是人间的四月天',
    content: '你是一树一树的花开，是燕在梁间呢喃，——你是爱，是暖，是希望，你是人间的四月天！',
    emotionTags: ['温暖', '希望', '爱'],
    imageryTags: ['花', '燕子'],
    sceneTags: ['春天'],
    themeTags: ['爱情', '生命'],
  },

  // ========== 莎士比亚 ==========
  {
    authorName: '莎士比亚',
    workTitle: '哈姆雷特',
    content: '生存还是毁灭，这是一个值得考虑的问题。',
    emotionTags: ['困惑', '沉思', '挣扎'],
    imageryTags: [],
    sceneTags: ['内心'],
    themeTags: ['人生', '选择'],
  },
  {
    authorName: '莎士比亚',
    workTitle: '哈姆雷特',
    content: '脆弱啊，你的名字是女人！',
    emotionTags: ['悲伤', '失望', '感慨'],
    imageryTags: [],
    sceneTags: ['内心'],
    themeTags: ['人性', '情感'],
  },
  {
    authorName: '莎士比亚',
    workTitle: '十四行诗',
    content: '我怎么能够把你来比作夏天？你不独比它可爱也比它温婉。',
    emotionTags: ['爱慕', '温柔', '赞美'],
    imageryTags: ['夏天'],
    sceneTags: ['自然'],
    themeTags: ['爱情', '美'],
  },
  {
    authorName: '莎士比亚',
    workTitle: '十四行诗',
    content: '只要一天有人类，或人有眼睛，这诗将长存，并且赐给你生命。',
    emotionTags: ['坚定', '永恒', '深情'],
    imageryTags: [],
    sceneTags: ['内心'],
    themeTags: ['爱情', '永恒'],
  },

  // ========== 泰戈尔 ==========
  {
    authorName: '泰戈尔',
    workTitle: '飞鸟集',
    content: '世界以痛吻我，要我报之以歌。',
    emotionTags: ['坚强', '豁达', '温暖'],
    imageryTags: [],
    sceneTags: ['内心'],
    themeTags: ['人生', '态度'],
  },
  {
    authorName: '泰戈尔',
    workTitle: '飞鸟集',
    content: '生如夏花之绚烂，死如秋叶之静美。',
    emotionTags: ['超脱', '平静', '哲思'],
    imageryTags: ['夏花', '秋叶'],
    sceneTags: ['自然'],
    themeTags: ['生死', '人生'],
  },
  {
    authorName: '泰戈尔',
    workTitle: '飞鸟集',
    content: '我们把世界看错了，反说它欺骗我们。',
    emotionTags: ['深刻', '反思', '智慧'],
    imageryTags: [],
    sceneTags: ['内心'],
    themeTags: ['认知', '哲理'],
  },
  {
    authorName: '泰戈尔',
    workTitle: '新月集',
    content: '只有经历过地狱般的磨砺，才能练就创造天堂的力量；只有流过血的手指，才能弹出世间的绝响。',
    emotionTags: ['坚强', '励志', '深刻'],
    imageryTags: ['地狱', '天堂', '手指'],
    sceneTags: ['内心'],
    themeTags: ['成长', '磨难'],
  },

  // ========== 海明威 ==========
  {
    authorName: '海明威',
    workTitle: '老人与海',
    content: '一个人可以被毁灭，但不能被打败。',
    emotionTags: ['坚强', '不屈', '勇敢'],
    imageryTags: [],
    sceneTags: ['内心'],
    themeTags: ['意志', '尊严'],
  },
  {
    authorName: '海明威',
    workTitle: '老人与海',
    content: '现在不是去想缺少什么的时候，该想一想凭现有的东西你能做什么。',
    emotionTags: ['务实', '坚定', '冷静'],
    imageryTags: [],
    sceneTags: ['内心'],
    themeTags: ['行动', '态度'],
  },
  {
    authorName: '海明威',
    workTitle: '老人与海',
    content: '每一天都是一个新的日子。走运当然是好的，不过我情愿做到分毫不差。这样，运气来的时候，你就有所准备了。',
    emotionTags: ['从容', '准备', '智慧'],
    imageryTags: [],
    sceneTags: ['内心'],
    themeTags: ['人生', '准备'],
  },

  // ========== 川端康成 ==========
  {
    authorName: '川端康成',
    workTitle: '雪国',
    content: '穿过县界长长的隧道，便是雪国。夜空下一片白茫茫。火车在信号所前停了下来。',
    emotionTags: ['宁静', '孤寂', '唯美'],
    imageryTags: ['隧道', '雪', '夜空', '火车'],
    sceneTags: ['冬天', '旅途'],
    themeTags: ['旅行', '孤独'],
  },
  {
    authorName: '川端康成',
    workTitle: '雪国',
    content: '凌晨四点钟，看到海棠花未眠。',
    emotionTags: ['宁静', '细腻', '感动'],
    imageryTags: ['海棠花', '凌晨'],
    sceneTags: ['清晨'],
    themeTags: ['美', '生命'],
  },
  {
    authorName: '川端康成',
    workTitle: '古都',
    content: '美，一旦在这个世界上表现出来，就不会泯灭。',
    emotionTags: ['感悟', '永恒', '唯美'],
    imageryTags: [],
    sceneTags: ['内心'],
    themeTags: ['美', '永恒'],
  },

  // ========== 加缪 ==========
  {
    authorName: '加缪',
    workTitle: '局外人',
    content: '我知道这世界我无处容身，只是，你凭什么审判我的灵魂？',
    emotionTags: ['反抗', '孤独', '质疑'],
    imageryTags: [],
    sceneTags: ['内心'],
    themeTags: ['存在', '自由'],
  },
  {
    authorName: '加缪',
    workTitle: '局外人',
    content: '人们永远也无法改变生活，什么样的生活都差不多，而我在这里的生活并不使我厌烦。',
    emotionTags: ['冷漠', '超脱', '接受'],
    imageryTags: [],
    sceneTags: ['内心'],
    themeTags: ['人生', '态度'],
  },
  {
    authorName: '加缪',
    workTitle: '西西弗神话',
    content: '应该想象西西弗是幸福的。',
    emotionTags: ['荒诞', '反抗', '希望'],
    imageryTags: ['西西弗', '巨石'],
    sceneTags: ['神话'],
    themeTags: ['存在', '意义'],
  },
  {
    authorName: '加缪',
    workTitle: '西西弗神话',
    content: '真正严肃的哲学问题只有一个，那就是自杀。判断人生值不值得活，等于回答哲学的根本问题。',
    emotionTags: ['深刻', '严肃', '哲思'],
    imageryTags: [],
    sceneTags: ['内心'],
    themeTags: ['存在', '意义'],
  },
  {
    authorName: '加缪',
    workTitle: '西西弗神话',
    content: '在隆冬，我终于知道，我身上有一个不可战胜的夏天。',
    emotionTags: ['希望', '坚强', '温暖'],
    imageryTags: ['冬天', '夏天'],
    sceneTags: ['内心'],
    themeTags: ['希望', '力量'],
  },
];
